name: Build printable files

on:
  push:
    paths:
      - '**.scad'
      - '**.ini'
    branches:
     - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        printer: [mini, edee, mlab3d]
    env:
      OPENSCAD_BIN: xvfb-run --auto-servernum ~/OpenSCAD.AppImage
      SLIC3R_BIN: ~/Slic3r.AppImage
      PRINTER: ${{ matrix.printer }}
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    # - uses: hmarr/debug-action@v2

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUBPAT }}
        submodules: recursive

    - name: Install requirements
      run: |
        sudo apt-get update
        wget https://dl.slic3r.org/linux/Slic3r-1.3.0-x86_64.AppImage -O ~/Slic3r.AppImage
        chmod +x ~/Slic3r.AppImage
        wget https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage -O ~/OpenSCAD.AppImage
        chmod +x ~/OpenSCAD.AppImage
        sudo apt-get install libc-bin python3-setuptools xvfb
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install stlsort lxml
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv@a541869d11d3c094f1d7a3ed4d3c0c30489398e9
        sudo python3 -m pip install git+https://${{ secrets.AUTH_USER }}:${{ secrets.GITHUBPAT }}@github.com/ThunderFly-aerospace/processor3D.git

    - name: Make
      run: |
        cd CAD/src/printplate; make

    - name: Upload a AMF Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: 'render_amf'
        path: './**/*.amf'

    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Upload gcodes
      uses:  MLAB-project/push-generated-file@master
      with:
        source_file_path: 'CAD/gcode'
        destination_folder: 'gcode'
        destination_repo: 'ThunderFly-aerospace/gcodes'
        target_branch:  ${{env.CI_REPOSITORY}}/${{env.CI_REF_NAME}}/${{matrix.printer}}
        token: ${{ secrets.GITHUBPAT }}

#     - name: Upload images
#       uses:  MLAB-project/push-generated-file@master
#       with:
#         source_file_path: 'CAD/img'
#         destination_folder: 'png'
#         destination_repo: 'ThunderFly-aerospace/gcodes'
#         target_branch:  TF-G2/${{github.ref}}/${{matrix.printer}}
#         token: ${{ secrets.GITHUBPAT }}
